import XCTest

@testable import ArcShot

@MainActor
final class LocalizationTests: XCTestCase {
  func testAppLanguageStorePersistsSelectedLanguage() {
    let defaults = UserDefaults(suiteName: "dev.arcshot.tests.localization.\(UUID().uuidString)")!
    defaults.removeObject(forKey: AppIdentifiers.UserDefaultsKeys.appLanguage)

    let store = AppLanguageStore(defaults: defaults)
    XCTAssertEqual(store.language, .english)

    store.language = .japanese
    XCTAssertEqual(defaults.string(forKey: AppIdentifiers.UserDefaultsKeys.appLanguage), "ja")
    XCTAssertEqual(AppLanguageStore(defaults: defaults).language, .japanese)
  }

  func testAppLanguageStoreResolvesEnglishResourceString() {
    let defaults = UserDefaults(suiteName: "dev.arcshot.tests.localization.\(UUID().uuidString)")!
    defaults.set("en", forKey: AppIdentifiers.UserDefaultsKeys.appLanguage)

    let store = AppLanguageStore(defaults: defaults)
    XCTAssertEqual(store.localized("録画を停止"), "Stop Recording")
    XCTAssertEqual(store.localizedFormat("状態: %@", "Recording"), "State: Recording")
    XCTAssertEqual(store.localized("Display Language"), "Display Language")
    XCTAssertEqual(store.localized("Settings"), "Settings")
    XCTAssertEqual(store.localizedFormat("Masks are limited to %d.", 8), "Masks are limited to 8.")
    XCTAssertEqual(store.localized("映像"), "Video")
    XCTAssertEqual(store.localized("音声"), "Audio")
    XCTAssertEqual(store.localized("クリップ"), "Clip")
    XCTAssertEqual(store.localized("ズーム"), "Zoom")
    XCTAssertEqual(store.localized("マスク"), "Mask")
    XCTAssertEqual(store.localized("ライブラリ"), "Library")
    XCTAssertEqual(store.localized("ストレージ"), "Storage")
    XCTAssertEqual(store.localized("一覧を更新"), "Refresh")
    XCTAssertEqual(store.localizedFormat("%d 件のプロジェクト · %@", 3, "12 MB"), "3 projects · 12 MB")
  }

  func testAppLanguageStoreResolvesJapaneseResourceString() {
    let defaults = UserDefaults(suiteName: "dev.arcshot.tests.localization.\(UUID().uuidString)")!
    defaults.set("ja", forKey: AppIdentifiers.UserDefaultsKeys.appLanguage)

    let store = AppLanguageStore(defaults: defaults)
    XCTAssertEqual(store.localized("Display Language"), "表示言語")
    XCTAssertEqual(store.localized("Settings"), "設定")
    XCTAssertEqual(store.localizedFormat("Masks are limited to %d.", 8), "マスクは最大8個まで追加できます。")
  }

  func testLocalizedProjectDisplayTitleUsesEnglishForAutoGeneratedJapaneseTitle() {
    var calendar = Calendar(identifier: .gregorian)
    calendar.timeZone = TimeZone(secondsFromGMT: 0)!
    var components = DateComponents()
    components.year = 2026
    components.month = 6
    components.day = 22
    components.hour = 7
    components.minute = 51
    let createdAt = calendar.date(from: components)!

    let storedTitle = RecordingProject.formattedAutoTitle(
      createdAt: createdAt,
      recordingLabel: RecordingProject.autoTitlePrefixJapanese,
      locale: Locale(identifier: "ja_JP")
    )

    let defaults = UserDefaults(suiteName: "dev.arcshot.tests.localization.\(UUID().uuidString)")!
    defaults.set("en", forKey: AppIdentifiers.UserDefaultsKeys.appLanguage)
    let store = AppLanguageStore(defaults: defaults)

    let displayTitle = store.localizedProjectDisplayTitle(storedTitle: storedTitle, createdAt: createdAt)
    XCTAssertTrue(displayTitle.hasPrefix("Recording "))
    XCTAssertFalse(displayTitle.hasPrefix("収録 "))
  }

  func testLocalizedProjectDisplayTitlePreservesCustomTitle() {
    let createdAt = Date(timeIntervalSince1970: 1_700_000_000)
    let customTitle = "Demo walkthrough"

    let defaults = UserDefaults(suiteName: "dev.arcshot.tests.localization.\(UUID().uuidString)")!
    defaults.set("en", forKey: AppIdentifiers.UserDefaultsKeys.appLanguage)
    let store = AppLanguageStore(defaults: defaults)

    XCTAssertEqual(
      store.localizedProjectDisplayTitle(storedTitle: customTitle, createdAt: createdAt),
      customTitle
    )
  }
}
